/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#0b1c30",
        "surface-dim": "#d9d9e5",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#c5d6f0",
        "inverse-on-surface": "#f0f0fb",
        "inverse-primary": "#b7c4ff",
        "on-surface": "#1a1b23",
        "error-container": "#ffdad6",
        "surface-bright": "#faf8ff",
        "surface": "#faf8ff",
        "on-tertiary-fixed-variant": "#38485d",
        "on-background": "#1a1b23",
        "tertiary-fixed-dim": "#b7c8e1",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#131b2e",
        "tertiary-fixed": "#d3e4fe",
        "surface-container-highest": "#e2e1ed",
        "inverse-surface": "#2e3039",
        "primary-fixed": "#dce1ff",
        "primary-container": "#1d4ed8",
        "secondary-container": "#dae2fd",
        "on-secondary-container": "#5c647a",
        "on-error": "#ffffff",
        "surface-container-low": "#f3f2fe",
        "outline-variant": "#c4c5d7",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#cad3ff",
        "on-secondary-fixed-variant": "#3f465c",
        "tertiary": "#36455b",
        "surface-variant": "#e2e1ed",
        "secondary": "#565e74",
        "on-error-container": "#93000a",
        "tertiary-container": "#4d5d73",
        "background": "#faf8ff",
        "on-surface-variant": "#434655",
        "surface-container-high": "#e8e7f3",
        "surface-tint": "#2151da",
        "primary-fixed-dim": "#b7c4ff",
        "primary": "#0037b0",
        "secondary-fixed": "#dae2fd",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#bec6e0",
        "on-primary-fixed": "#001551",
        "on-primary-fixed-variant": "#0039b5",
        "on-primary": "#ffffff",
        "outline": "#747686",
        "surface-container": "#ededf9"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "margin-desktop": "32px",
        "container-max": "1440px",
        "margin-mobile": "16px",
        "unit": "8px",
        "gutter": "16px"
      },
      fontFamily: {
        "headline-lg": ["Inter"],
        "label-md": ["Inter"],
        "label-sm": ["Inter"],
        "headline-sm": ["Inter"],
        "label-lg": ["Inter"],
        "headline-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "body-lg": ["Inter"],
        "body-sm": ["Inter"],
        "body-md": ["Inter"]
      },
      fontSize: {
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.04em", "fontWeight": "600" }],
        "label-sm": ["11px", { "lineHeight": "14px", "letterSpacing": "0.05em", "fontWeight": "700" }],
        "headline-sm": ["20px", { "lineHeight": "28px", "letterSpacing": "0em", "fontWeight": "600" }],
        "label-lg": ["14px", { "lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "body-lg": ["16px", { "lineHeight": "24px", "letterSpacing": "0em", "fontWeight": "400" }],
        "body-sm": ["13px", { "lineHeight": "18px", "letterSpacing": "0em", "fontWeight": "400" }],
        "body-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0em", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}

